from datetime import datetime, timezone
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

# ── Player Data Layer ──────────────────────────────────────────────────────────

# ── SSoT Data Layer ────────────────────────────────────────────────────────────


class Competition(db.Model):
    __tablename__ = 'competitions'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    country = db.Column(db.String(100))
    season = db.Column(db.String(20), nullable=False)
    source_id = db.Column(db.String(50))
    source_name = db.Column(db.String(50))

    __table_args__ = (
        db.UniqueConstraint('name', 'season', name='uq_competition_season'),
    )

    def __repr__(self):
        return f'<Competition {self.name} {self.season}>'


class Team(db.Model):
    __tablename__ = 'teams'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    short_name = db.Column(db.String(50))
    country = db.Column(db.String(100))
    competition_id = db.Column(db.Integer, db.ForeignKey('competitions.id'))
    source_id = db.Column(db.String(50))
    source_name = db.Column(db.String(50))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('source_id', 'source_name', name='uq_team_source'),
    )

    def __repr__(self):
        return f'<Team {self.name}>'


class Player(db.Model):
    __tablename__ = 'players'
    id = db.Column(db.Integer, primary_key=True)
    # Core identity (legacy — kept for backward compat with existing workers)
    name = db.Column(db.String(120), nullable=False)
    nationality = db.Column(db.String(80))
    position = db.Column(db.String(50))        # GK | DEF | MID | ATT
    age = db.Column(db.Integer)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    source_id = db.Column(db.String(50))       # api-football player id
    source_name = db.Column(db.String(50))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    # Extended identity (Layer 1)
    name_full = db.Column(db.String(200))
    name_short = db.Column(db.String(100))
    nationality_iso2 = db.Column(db.String(2))
    date_of_birth = db.Column(db.Date)
    height_cm = db.Column(db.Integer)
    weight_kg = db.Column(db.Integer)
    foot_dominant = db.Column(db.String(10))   # left | right | both
    shirt_number = db.Column(db.Integer)
    contract_until = db.Column(db.Date)
    is_active = db.Column(db.Boolean, default=True)

    # External IDs for cross-source mapping
    external_id_understat = db.Column(db.Integer)
    external_id_transfermarkt = db.Column(db.String(50))
    external_id_fbref = db.Column(db.String(100))
    external_id_sportsdb = db.Column(db.String(50))

    # Photo assets (Layer 1 visual)
    photo_url_local = db.Column(db.String(500))          # CDN/local proxy (preferred)
    photo_url_apifootball = db.Column(db.String(500))
    photo_url_sportsdb_thumb = db.Column(db.String(500))
    photo_url_sportsdb_cutout = db.Column(db.String(500))

    # Bio (Layer 4 narrative)
    bio_text = db.Column(db.Text)   # crowd-sourced from TheSportsDB
    bio_llm = db.Column(db.Text)    # generated by LLM, updated monthly

    __table_args__ = (
        db.UniqueConstraint('source_id', 'source_name', name='uq_player_source'),
    )

    def __repr__(self):
        return f'<Player {self.name}>'


class Fixture(db.Model):
    __tablename__ = 'fixtures'
    id = db.Column(db.Integer, primary_key=True)
    competition_id = db.Column(db.Integer, db.ForeignKey('competitions.id'), nullable=False)
    home_team_id = db.Column(db.Integer, db.ForeignKey('teams.id'), nullable=False)
    away_team_id = db.Column(db.Integer, db.ForeignKey('teams.id'), nullable=False)
    scheduled_at = db.Column(db.DateTime)
    status = db.Column(db.String(20), default='scheduled')  # scheduled|live|finished|postponed
    home_score = db.Column(db.Integer)
    away_score = db.Column(db.Integer)
    source_primary = db.Column(db.String(50))
    source_id = db.Column(db.String(50))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    competition = db.relationship('Competition', backref='fixtures')
    home_team = db.relationship('Team', foreign_keys=[home_team_id])
    away_team = db.relationship('Team', foreign_keys=[away_team_id])

    __table_args__ = (
        db.UniqueConstraint('source_id', 'source_primary', name='uq_fixture_source'),
    )

    def __repr__(self):
        return f'<Fixture {self.home_team_id}x{self.away_team_id} {self.scheduled_at}>'


class MatchStats(db.Model):
    __tablename__ = 'match_stats'
    id = db.Column(db.Integer, primary_key=True)
    fixture_id = db.Column(db.Integer, db.ForeignKey('fixtures.id'), nullable=False)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    player_id = db.Column(db.Integer, db.ForeignKey('players.id'))
    goals = db.Column(db.Integer, default=0)
    assists = db.Column(db.Integer, default=0)
    shots = db.Column(db.Integer)
    shots_on_target = db.Column(db.Integer)
    passes = db.Column(db.Integer)
    pass_accuracy = db.Column(db.Float)
    yellow_cards = db.Column(db.Integer, default=0)
    red_cards = db.Column(db.Integer, default=0)
    minutes_played = db.Column(db.Integer)
    source_name = db.Column(db.String(50))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('fixture_id', 'player_id', 'source_name', name='uq_match_stats_entry'),
    )

    def __repr__(self):
        return f'<MatchStats fixture={self.fixture_id} player={self.player_id}>'


class AdvancedMetrics(db.Model):
    __tablename__ = 'advanced_metrics'
    id = db.Column(db.Integer, primary_key=True)
    # fixture_id is NULL for season-aggregate rows (Understat season totals)
    fixture_id = db.Column(db.Integer, db.ForeignKey('fixtures.id'), nullable=True)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    player_id = db.Column(db.Integer, db.ForeignKey('players.id'))
    xg = db.Column(db.Float)
    xa = db.Column(db.Float)
    npxg = db.Column(db.Float)
    xg_chain = db.Column(db.Float)
    xg_buildup = db.Column(db.Float)
    progressive_passes = db.Column(db.Integer)
    pressures = db.Column(db.Integer)
    defensive_actions = db.Column(db.Integer)
    source_name = db.Column(db.String(50))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f'<AdvancedMetrics fixture={self.fixture_id} player={self.player_id}>'


class TeamForm(db.Model):
    __tablename__ = 'team_form'
    id = db.Column(db.Integer, primary_key=True)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'), nullable=False)
    competition_id = db.Column(db.Integer, db.ForeignKey('competitions.id'), nullable=False)
    last_5 = db.Column(db.String(20))   # e.g. "WWDLW"
    last_10 = db.Column(db.String(20))  # e.g. "WWDLWWDLWW"
    wins = db.Column(db.Integer, default=0)
    draws = db.Column(db.Integer, default=0)
    losses = db.Column(db.Integer, default=0)
    goals_scored = db.Column(db.Integer, default=0)
    goals_conceded = db.Column(db.Integer, default=0)
    xg_avg = db.Column(db.Float)
    xga_avg = db.Column(db.Float)
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('team_id', 'competition_id', name='uq_team_form'),
    )

    def __repr__(self):
        return f'<TeamForm team={self.team_id} comp={self.competition_id}>'


class DataConflict(db.Model):
    __tablename__ = 'data_conflicts'
    id = db.Column(db.Integer, primary_key=True)
    entity_type = db.Column(db.String(50), nullable=False)  # fixture|player|match_stats
    entity_id = db.Column(db.Integer, nullable=False)
    field_name = db.Column(db.String(50), nullable=False)
    value_primary = db.Column(db.String(200))
    value_fallback = db.Column(db.String(200))
    delta = db.Column(db.Float)
    source_primary = db.Column(db.String(50))
    source_fallback = db.Column(db.String(50))
    detected_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    resolved = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f'<DataConflict {self.entity_type}#{self.entity_id}.{self.field_name}>'

roles_users = db.Table(
    'roles_users',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), primary_key=True),
    db.Column('role_id', db.Integer, db.ForeignKey('role.id', ondelete='CASCADE'), primary_key=True),
)


class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    description = db.Column(db.String(255))

    def __str__(self):
        return self.name


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    senha = db.Column(db.String(512), nullable=False)
    active = db.Column(db.Boolean, default=True)
    tier = db.Column(db.String(20), default='standard')  # standard | pro | max
    criado_em = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

    def has_role(self, role_name: str) -> bool:
        return any(r.name == role_name for r in self.roles)

    def __repr__(self):
        return f'<User {self.email}>'


class Partida(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    statsbomb_id = db.Column(db.Integer, unique=True)
    time_casa = db.Column(db.String(100), nullable=False)
    time_visitante = db.Column(db.String(100), nullable=False)
    competicao = db.Column(db.String(100), nullable=False)
    temporada = db.Column(db.String(20), nullable=False)
    rodada = db.Column(db.Integer)
    data_partida = db.Column(db.DateTime)
    status = db.Column(db.String(20), default='agendada')  # agendada | encerrada
    stats_json = db.Column(db.Text)

    def stats(self):
        import json
        return json.loads(self.stats_json) if self.stats_json else {}

    def __repr__(self):
        return f'<Partida {self.time_casa} x {self.time_visitante}>'


class Jogador(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    statsbomb_id = db.Column(db.Integer, unique=True)
    nome = db.Column(db.String(120), nullable=False)
    time_atual = db.Column(db.String(100))
    nacionalidade = db.Column(db.String(80))
    posicao = db.Column(db.String(50))
    stats_json = db.Column(db.Text)
    temporada = db.Column(db.String(20))
    ativo = db.Column(db.Boolean, default=True)

    def __repr__(self):
        return f'<Jogador {self.nome}>'


class Relatorio(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    tipo = db.Column(db.String(30), nullable=False)
    # pre_torcedor | pre_profissional | pos | jogador | locutor
    partida_id = db.Column(db.Integer, db.ForeignKey('partida.id'), nullable=True)
    fixture_id = db.Column(db.Integer, db.ForeignKey('fixtures.id'), nullable=True)
    jogador_id = db.Column(db.Integer, db.ForeignKey('jogador.id'), nullable=True)
    conteudo = db.Column(db.Text, nullable=False)
    gerado_em = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    user_tier_minimo = db.Column(db.String(20), default='standard')

    partida = db.relationship('Partida', backref='relatorios')
    fixture = db.relationship('Fixture', backref='relatorios')

    def __repr__(self):
        return f'<Relatorio {self.tipo} partida={self.partida_id}>'


class Noticia(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(500), nullable=False)
    url = db.Column(db.String(500), unique=True, nullable=False)
    fonte = db.Column(db.String(100))
    publicada_em = db.Column(db.DateTime)
    resumo_impacto = db.Column(db.Text)
    time_relacionado = db.Column(db.String(100))
    jogador_relacionado = db.Column(db.String(120))
    impacto_processado = db.Column(db.Boolean, default=False)
    criada_em = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f'<Noticia {self.titulo[:40]}>'


class ContextoHistorico(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    time1 = db.Column(db.String(100), nullable=False)
    time2 = db.Column(db.String(100), nullable=False)
    narrativa = db.Column(db.Text)
    atualizado_em = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f'<ContextoHistorico {self.time1} vs {self.time2}>'


# ── Player Data Layer: Season, Market, Percentiles, ID Mapping ─────────────────


class PlayerSeasonStats(db.Model):
    """Aggregated stats per player / competition / season. Layer 2 + 3."""
    __tablename__ = 'player_season_stats'
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey('players.id', ondelete='CASCADE'), nullable=False)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    competition_id = db.Column(db.Integer, db.ForeignKey('competitions.id'))
    season = db.Column(db.String(10), nullable=False)  # "2024-25"

    # Volume
    appearances = db.Column(db.Integer, default=0)
    starts = db.Column(db.Integer, default=0)
    minutes_played = db.Column(db.Integer, default=0)

    # Attack
    goals = db.Column(db.Integer, default=0)
    assists = db.Column(db.Integer, default=0)
    shots_total = db.Column(db.Integer, default=0)
    shots_on_target = db.Column(db.Integer, default=0)
    shot_accuracy_pct = db.Column(db.Numeric(5, 2))

    # Passing
    passes_total = db.Column(db.Integer, default=0)
    pass_accuracy_pct = db.Column(db.Numeric(5, 2))
    key_passes = db.Column(db.Integer, default=0)

    # Dribbles & duels
    dribbles_attempted = db.Column(db.Integer, default=0)
    dribbles_success = db.Column(db.Integer, default=0)
    duels_total = db.Column(db.Integer, default=0)
    duels_won = db.Column(db.Integer, default=0)
    aerial_duels_won = db.Column(db.Integer, default=0)

    # Discipline
    yellow_cards = db.Column(db.Integer, default=0)
    red_cards = db.Column(db.Integer, default=0)
    fouls_committed = db.Column(db.Integer, default=0)
    fouls_drawn = db.Column(db.Integer, default=0)

    # Advanced (Understat)
    xg = db.Column(db.Numeric(6, 3))
    xa = db.Column(db.Numeric(6, 3))
    npxg = db.Column(db.Numeric(6, 3))
    xg_chain = db.Column(db.Numeric(6, 3))
    xg_buildup = db.Column(db.Numeric(6, 3))

    # Per-90 (computed by worker)
    xg_per90 = db.Column(db.Numeric(5, 3))
    xa_per90 = db.Column(db.Numeric(5, 3))
    goals_per90 = db.Column(db.Numeric(5, 3))
    assists_per90 = db.Column(db.Numeric(5, 3))

    # FBref metrics (weekly scrape)
    progressive_carries = db.Column(db.Integer)
    progressive_passes_fbref = db.Column(db.Integer)
    pressures = db.Column(db.Integer)
    defensive_actions = db.Column(db.Integer)

    rating_avg = db.Column(db.Numeric(4, 2))

    source_base = db.Column(db.String(50), default='api-football')
    source_advanced = db.Column(db.String(50), default='understat')
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('player_id', 'competition_id', 'season', name='uq_player_season_comp'),
    )

    def __repr__(self):
        return f'<PlayerSeasonStats player={self.player_id} season={self.season}>'


class PlayerMarketValue(db.Model):
    """Historical market value snapshots from Transfermarkt. Layer 4."""
    __tablename__ = 'player_market_value'
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey('players.id', ondelete='CASCADE'), nullable=False)
    value_eur = db.Column(db.BigInteger)
    value_date = db.Column(db.Date, nullable=False)
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    source = db.Column(db.String(50), default='transfermarkt')
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('player_id', 'value_date', name='uq_player_market_date'),
    )

    def __repr__(self):
        return f'<PlayerMarketValue player={self.player_id} val={self.value_eur}>'


class PlayerPercentiles(db.Model):
    """Per-metric percentile ranks vs peers in the same position+league+season."""
    __tablename__ = 'player_percentiles'
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey('players.id', ondelete='CASCADE'), nullable=False)
    competition_id = db.Column(db.Integer, db.ForeignKey('competitions.id'))
    season = db.Column(db.String(10))
    position_group = db.Column(db.String(20))  # GK | DEF | MID | ATT

    pct_goals = db.Column(db.SmallInteger)
    pct_assists = db.Column(db.SmallInteger)
    pct_xg = db.Column(db.SmallInteger)
    pct_xa = db.Column(db.SmallInteger)
    pct_xg_per90 = db.Column(db.SmallInteger)
    pct_progressive_passes = db.Column(db.SmallInteger)
    pct_progressive_carries = db.Column(db.SmallInteger)
    pct_pressures = db.Column(db.SmallInteger)
    pct_pass_accuracy = db.Column(db.SmallInteger)
    pct_aerial_duels_won = db.Column(db.SmallInteger)
    pct_dribbles_success = db.Column(db.SmallInteger)

    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('player_id', 'competition_id', 'season', name='uq_player_percentiles'),
    )

    def __repr__(self):
        return f'<PlayerPercentiles player={self.player_id} season={self.season}>'


class PlayerIdMapping(db.Model):
    """Cross-source ID mapping table. Maps internal player_id to external source IDs."""
    __tablename__ = 'player_id_mapping'
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey('players.id', ondelete='CASCADE'), nullable=False)
    source = db.Column(db.String(50), nullable=False)      # understat | sportsdb | transfermarkt | fbref
    external_id = db.Column(db.String(100), nullable=False)
    confidence = db.Column(db.String(20), default='auto')  # auto | manual | verified
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        db.UniqueConstraint('source', 'external_id', name='uq_player_id_mapping'),
    )

    def __repr__(self):
        return f'<PlayerIdMapping player={self.player_id} {self.source}={self.external_id}>'
