"""initial

Revision ID: 766b4f44ebb8
Revises: 
Create Date: 2026-04-27 00:22:37.817383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766b4f44ebb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_id_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_player_id_mapping')
    )
    op.create_table('player_market_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('value_eur', sa.BigInteger(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'value_date', name='uq_player_market_date')
    )
    op.create_table('player_percentiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('position_group', sa.String(length=20), nullable=True),
    sa.Column('pct_goals', sa.SmallInteger(), nullable=True),
    sa.Column('pct_assists', sa.SmallInteger(), nullable=True),
    sa.Column('pct_xg', sa.SmallInteger(), nullable=True),
    sa.Column('pct_xa', sa.SmallInteger(), nullable=True),
    sa.Column('pct_xg_per90', sa.SmallInteger(), nullable=True),
    sa.Column('pct_progressive_passes', sa.SmallInteger(), nullable=True),
    sa.Column('pct_progressive_carries', sa.SmallInteger(), nullable=True),
    sa.Column('pct_pressures', sa.SmallInteger(), nullable=True),
    sa.Column('pct_pass_accuracy', sa.SmallInteger(), nullable=True),
    sa.Column('pct_aerial_duels_won', sa.SmallInteger(), nullable=True),
    sa.Column('pct_dribbles_success', sa.SmallInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season', name='uq_player_percentiles')
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('starts', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('shot_accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('pass_accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=True),
    sa.Column('dribbles_success', sa.Integer(), nullable=True),
    sa.Column('duels_total', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('aerial_duels_won', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('fouls_drawn', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('xa', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('npxg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('xg_chain', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('xg_buildup', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('xg_per90', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('xa_per90', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('goals_per90', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('assists_per90', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('progressive_carries', sa.Integer(), nullable=True),
    sa.Column('progressive_passes_fbref', sa.Integer(), nullable=True),
    sa.Column('pressures', sa.Integer(), nullable=True),
    sa.Column('defensive_actions', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('source_base', sa.String(length=50), nullable=True),
    sa.Column('source_advanced', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season', name='uq_player_season_comp')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_full', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('name_short', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nationality_iso2', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('foot_dominant', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('shirt_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('external_id_understat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('external_id_transfermarkt', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_id_fbref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_id_sportsdb', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo_url_local', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_url_apifootball', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_url_sportsdb_thumb', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_url_sportsdb_cutout', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bio_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio_llm', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('bio_llm')
        batch_op.drop_column('bio_text')
        batch_op.drop_column('photo_url_sportsdb_cutout')
        batch_op.drop_column('photo_url_sportsdb_thumb')
        batch_op.drop_column('photo_url_apifootball')
        batch_op.drop_column('photo_url_local')
        batch_op.drop_column('external_id_sportsdb')
        batch_op.drop_column('external_id_fbref')
        batch_op.drop_column('external_id_transfermarkt')
        batch_op.drop_column('external_id_understat')
        batch_op.drop_column('is_active')
        batch_op.drop_column('contract_until')
        batch_op.drop_column('shirt_number')
        batch_op.drop_column('foot_dominant')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('nationality_iso2')
        batch_op.drop_column('name_short')
        batch_op.drop_column('name_full')

    op.drop_table('player_season_stats')
    op.drop_table('player_percentiles')
    op.drop_table('player_market_value')
    op.drop_table('player_id_mapping')
    # ### end Alembic commands ###
